config:
  exporters:
    azuremonitor: {}
    jaeger:
      endpoint: jaeger-all-in-one:14250
      insecure: true
  receivers:
    jaeger: null
    zipkin: null
  service:
    pipelines:
      traces:
        exporters:
          - logging
          - azuremonitor
          - jaeger
        receivers:
          - otlp

image:
  repository: otel/opentelemetry-collector-contrib
  pullPolicy: IfNotPresent
  tag: 0.29.0
command:
  name: otelcontribcol

agentCollector:
  enabled: true
  resources:
    limits:
      cpu: 256m
      memory: 512Mi
    requests:
      cpu: 128m
      memory: 256Mi

standaloneCollector:
  enabled: true
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 128m
      memory: 256Mi

ports:
  jaeger-thrift: null
  jaeger-grpc: null
  zipkin: null
